name: clean_backend
version: 0.5.3
author: Clean Team <clean@vacuumlabs.com>
description: Basic server-side environment.
homepage: https://github.com/cleandart/clean_backend
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: https://github.com/cleandart/clean_backend
dependencies:
  clean_logging: any
  clean_router: '>=0.3.0 <0.5.0'
  crypto: '>=0.9.0 <0.10.0'
  hop_docgen: any
  http_server: '>=0.9.0 <0.10.0'
  path: '>=0.9.0 <2.0.0'
dev_dependencies:
  hop: any
  hop_unittest: any
  mock: any
  unittest: any
