name: clean_backend
author: Clean Team <clean@vacuumlabs.com>
version: 0.1.3
homepage: https://github.com/cleandart/clean_backend
description: Basic server-side environment.
documentation: https://github.com/cleandart/clean_backend
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  clean_router: '>=0.1.2 <0.2.0'
  crypto: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.0 <0.10.0'
  path: '>=0.9.0 <0.10.0'
dev_dependencies:
  hop: any
  unittest: any
